### ISSUE TITLE
How to Github

### ISSUE THREAD

**Issue by gaurav-gogia** [gaurav-gogia/pakdemon#11]

**Comment by kumaran-14** [comment]
I ll do this.

**Comment by rameshvishnoi90904** [comment]
done.

**Comment by SupaFresh** [comment]
I'm in

**Comment by SupaFresh** [comment]
done

**Comment by wissemgamra** [comment]
Done!

**Comment by theREALaltoid** [comment]
@SupaFresh I read the rules after I did those. Notice I've made three PR's since then and probably doing a fourth tonight. I was asking the question genuinely. I wasn't trying stir the pot. I was asking because I didn't want to people to think these counted and then end up not getting a shirt
